ENVIRONMENT = "production"
URL = "https://apps.dtic.mil/dodinvestment/#/advancedSearch"
SEARCH_ELEMENT_ID = "budgetNumObj_value"
SEARCH_VALUE = "0603680F"
BUTTON_ELEMENT_ID = "performSearch"
RESULTS_CLASS_NAME = "record-listing"
